from pydantic import BaseModel, Field
from typing import Optional, Literal, List, Any 
from datetime import datetime

# -------- Company context node -------
class CompanyContext(BaseModel):
    ticker: str
    # Identity
    company_name: str
    industry: str
    sector: str
    country: str
    exchange: str
    market_cap: Optional[float]
    # Business description
    business_summary: str
    business_type: str  # e.g. "Product", "Platform", "Services", "Holding"
    # Financial health (high-signal only)
    pe_ratio: Optional[float]
    forward_pe: Optional[float]
    debt_to_equity: Optional[float]
    profit_margin: Optional[float]
    operating_margin: Optional[float]
    revenue_growth: Optional[float]
    earnings_growth: Optional[float]
    # Stability & risk
    beta: Optional[float]
    cash_on_hand: Optional[float]
    total_debt: Optional[float]
    # Meta
    data_source: str
    last_updated: str

# ------- News articles node schema -------
class BusinessNewsArticle(BaseModel):
    # ---------- Source ----------
    title: str
    publisher: str
    url: str
    published_at: Optional[datetime]

    # ---------- Classification ----------
    timeframe: Literal["daily", "monthly"]
    relevance: Literal["company", "industry", "macro"]

    # ---------- LLM Summary ----------
    raw_summary: str = Field(
        description="LLM-generated factual summary of the article"
    )

    # ---------- Sentiment Signals ----------
    sentiment_score: Optional[float] = Field(
        description="Numerical sentiment score in range [-1, 1] generated by LLM"
    )

    sentiment_label: Literal[
        "very_bullish", "bullish", "neutral", "bearish", "very_bearish"
    ]

    # ---------- Trading Interpretation ----------
    directional_bias: Literal["bullish", "bearish", "neutral"]
    action_signal: Literal["buy", "sell", "hold"]

    impact_horizon: Literal[
        "intraday", "short_term", "medium_term", "long_term"
    ]

    # ---------- Confidence & Reasoning ----------
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="LLM confidence in interpretation"
    )

    reasoning: str = Field(
        description="Short explanation justifying sentiment and action"
    )

class CompanyNewsAnalysis(BaseModel):
    # ---------- Identification ----------
    ticker: str = Field(description="Stock ticker symbol")

    # ---------- Raw Article Intelligence ----------
    business_news_summaries: List[BusinessNewsArticle] = Field(
        description="List of per-article LLM analyses"
    )

    # ---------- Counts ----------
    total_articles: int
    daily_articles: int
    monthly_articles: int

    # ---------- Mechanical Aggregates ----------
    avg_sentiment_score: Optional[float] = Field(
        description="Mean sentiment score across articles"
    )

    sentiment_distribution: dict = Field(
        description="Count of sentiment labels (bullish, bearish, etc.)"
    )

    action_distribution: dict = Field(
        description="Count of action signals (buy, sell, hold)"
    )

    horizon_distribution: dict = Field(
        description="Count of impact horizons (intraday, short_term, long_term)"
    )

    avg_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Average confidence across all articles"
    )

    # ---------- Flags (Mechanical Rules Only) ----------
    veto_flag: bool = Field(
        description="True if ANY article contains a veto-level event"
    )

    veto_articles: List[str] = Field(
        description="Titles or URLs of articles triggering veto"
    )

    # ---------- Metadata ----------
    data_source: str = Field(default="yfinance")
    generated_at: datetime

# ------- Market articles node schema -------
class MarketNewsArticle(BaseModel):
    # ---------- Source ----------
    title: str
    publisher: str
    url: str
    published_at: Optional[datetime]

    # ---------- Classification ----------
    timeframe: Literal["daily", "monthly"]
    relevance: Literal["industry", "macro"]

    # Optional macro context
    macro_theme: Optional[
        Literal[
            "rates", "inflation", "growth", "recession",
            "liquidity", "geopolitics", "regulation",
            "commodities", "currency", "labor",
            "earnings_cycle", "unknown"
        ]
    ] = None

    # ---------- LLM Summary ----------
    raw_summary: str = Field(
        description="LLM-generated factual summary of the article"
    )

    # ---------- Sentiment Signals ----------
    sentiment_score: Optional[float] = Field(
        description="Numerical sentiment score in range [-1, 1] generated by LLM"
    )

    sentiment_label: Literal[
        "very_bullish", "bullish", "neutral", "bearish", "very_bearish"
    ]

    # ---------- Trading Interpretation ----------
    directional_bias: Literal["bullish", "bearish", "neutral"]
    action_signal: Literal["buy", "sell", "hold"]

    impact_horizon: Literal[
        "intraday", "short_term", "medium_term", "long_term"
    ]

    # ---------- Confidence & Reasoning ----------
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="LLM confidence in interpretation"
    )

    reasoning: str = Field(
        description="Short explanation justifying sentiment and action"
    )

class MarketNewsAnalysis(BaseModel):
    # ---------- Identification ----------
    ticker: str = Field(description="Stock ticker symbol")

    # ---------- Raw Article Intelligence ----------
    market_news_summaries: List[MarketNewsArticle] = Field(
        description="List of per-article LLM analyses"
    )

    # ---------- Counts ----------
    total_articles: int
    daily_articles: int
    monthly_articles: int

    # ---------- Mechanical Aggregates ----------
    avg_sentiment_score: Optional[float] = Field(
        description="Mean sentiment score across articles"
    )

    sentiment_distribution: dict = Field(
        description="Count of sentiment labels (bullish, bearish, etc.)"
    )

    action_distribution: dict = Field(
        description="Count of action signals (buy, sell, hold)"
    )

    horizon_distribution: dict = Field(
        description="Count of impact horizons (intraday, short_term, long_term)"
    )

    macro_theme_distribution: dict = Field(
        description="Count of macro themes (rates, inflation, growth, recession, liquidity, etc.)"
    )

    avg_confidence: float = Field(
        ge=0.0, le=1.0,
        description="Average confidence across all articles"
    )

    # ---------- Flags (Mechanical Rules Only) ----------
    veto_flag: bool = Field(
        description="True if ANY article contains a veto-level event"
    )

    veto_articles: List[str] = Field(
        description="Titles or URLs of articles triggering veto"
    )

    # ---------- Metadata ----------
    data_source: str = Field(default="yfinance")
    generated_at: datetime

class SupportingSignals(BaseModel):
    fundamentals: dict[str, Any]
    company_news: dict[str, Any]
    market_news: dict[str, Any]

class FundamentalAnalysis(BaseModel):
    ticker: str
    company_name: str

    market_bias: Literal["bullish", "very_bullish", "neutral", "bearish", "very_bearish"]
    action_signal: Literal["buy", "hold", "sell"]

    confidence: float  # 0.0–1.0

    reasoning: str
    main_points: list[str]

    supporting_signals: SupportingSignals

    generated_at: datetime